### ISSUE TITLE
Incompatible with bookshelf-uuid

### ISSUE THREAD

**Issue by ttencate** [oscaroox/bookshelf-slug#1]
The [bookshelf-uuid](https://github.com/estate/bookshelf-uuid) plugin generates IDs for models before they are saved to the database. This causes `model.isNew()` to return false, which triggers a database query (presumably to get the full model in case some fields were missing?). However, of course that query will return `null` for new models, and so we get:

```
  <rejected> TypeError: Cannot read property 'toJSON' of null
    at Child.constructor.forge.fetch.then.s (/home/thomas/wejam/node_modules/bookshelf-slug/lib/bookshelf-slug.js:52:52)
```

I'll send a PR.

**Comment by oscaroox** [comment]
hey @ttencate thanks for submitting a pull request, I've reviewed your changes and will merge them.
